name = "matthewwcook"
type = "webpack"
account_id = "b8ddb73a250de37cef756d9488336718"
route = "matthewwcook.com/*"
zone_id = "b9eb5c986c57b83e2ed3f66ca7f28f6b"

[site]
bucket = "./build"
entry-point = "workers-site"
